job_name: port-compressor-retry-3
jobs_dir: jobs
n_attempts: 1
timeout_multiplier: 1.0
orchestrator:
  type: local
  n_concurrent_trials: 8
  quiet: false
  retry:
    max_retries: 5
    include_exceptions: null
    exclude_exceptions:
    - AgentTimeoutError
    - VerifierTimeoutError
    wait_multiplier: 2.0
    min_wait_sec: 10.0
    max_wait_sec: 60.0
environment:
  type: daytona
  force_build: false
  delete: true
agents:
  - name: terminus-2
    model_name: together_ai/openai/gpt-oss-120b
datasets:
  - path: ../sandboxes/tasks/sandboxes-tasks
    task_names:
      - port-compressor
