jobs_dir: jobs
n_attempts: 1
timeout_multiplier: 1.0
orchestrator:
  type: local
  n_concurrent_trials: 100
  quiet: false
environment:
  type: daytona
  force_build: true
  delete: true
agents:
  - name: oracle
datasets:
  - path: ../working-tasks
