job_name: codex-cli-initial
jobs_dir: jobs
n_attempts: 5
timeout_multiplier: 1.0
orchestrator:
  type: local
  n_concurrent_trials: 200
  quiet: true
environment:
  type: daytona
  force_build: false
  delete: true
agents:
  - name: codex
    model_name: openai/gpt-5
  - name: codex
    model_name: openai/gpt-5-mini
  - name: codex
    model_name: openai/gpt-5-nano
datasets:
  - path: ../sandboxes/tasks/sandboxes-tasks
    exclude_task_names:
      - chem-rf
      - hf-lora-adapter
      - leelachess0-pytorch-conversion
      - mcmc-sampling-stan
      - oom
      - privilege-escalation
      - shell-deobfuscation
      - speech-to-text
      - unprivileged-headless-pyrender
      - build-linux-kernel-qemu
      - caffe-cifar-10
      - install-windows-xp
      - kv-store-grpc
      - lean4-proof
      - mailman
      - predicate-pushdown-bench
      - protocol-analysis-rs
      - query-optimize
      - rstan-to-pystan
      - torch-pipeline-parallelism
      - word2vec-from-scratch
