job_name: terminus-closed
jobs_dir: jobs
n_attempts: 5
timeout_multiplier: 1.0
orchestrator:
  type: local
  n_concurrent_trials: 100
  quiet: false
  retry:
    max_retries: 5
    exclude_exceptions:
      - AgentTimeoutError
      - VerifierTimeoutError
    wait_multiplier: 1.0
    min_wait_sec: 1.0
    max_wait_sec: 60.0
environment:
  type: daytona
  force_build: false
  delete: true
agents:
  - name: terminus-2
    model_name: anthropic/claude-sonnet-4-5-20250929
    kwargs:
      max_episodes: 200
  - name: terminus-2
    model_name: anthropic/claude-opus-4-1-20250805
    kwargs:
      max_episodes: 200
  - name: terminus-2
    model_name: anthropic/claude-haiku-4-5-20251001
    kwargs:
      max_episodes: 200
  - name: terminus-2
    model_name: openai/gpt-5-codex
    kwargs:
      max_episodes: 200
  - name: terminus-2
    model_name: openai/gpt-5
    kwargs:
      max_episodes: 200
  - name: terminus-2
    model_name: openai/gpt-5-mini
    kwargs:
      max_episodes: 200
  - name: terminus-2
    model_name: openai/gpt-5-nano
    kwargs:
      max_episodes: 200
  - name: terminus-2
    model_name: xai/grok-4-0709
    kwargs:
      max_episodes: 200
  - name: terminus-2
    model_name: xai/grok-code-fast-1
    kwargs:
      max_episodes: 200
  - name: terminus-2
    model_name: gemini/gemini-2.5-pro
    kwargs:
      max_episodes: 200
  - name: terminus-2
    model_name: gemini/gemini-2.5-flash
    kwargs:
      max_episodes: 200
datasets:
  - registry:
      name: harbor
      url: https://raw.githubusercontent.com/laude-institute/harbor/main/registry.json
    name: terminal-bench
    version: 2.0
