# job_name: 2025-09-15__01-26-06
jobs_dir: jobs
n_attempts: 1
timeout_multiplier: 1.0
orchestrator:
  type: local
  n_concurrent_trials: 400
  quiet: true
environment:
  type: daytona
  force_build: false
  delete: true
agents:
  - name: goose
    model_name: anthropic/claude-sonnet-4-20250514
  - name: goose
    model_name: anthropic/claude-opus-4-1-20250805
  - name: goose
    model_name: openai/gpt-5
  - name: goose
    model_name: openai/gpt-5-mini
  - name: goose
    model_name: openai/gpt-5-nano
  - name: goose
    model_name: xai/grok-4-0709
  - name: goose
    model_name: xai/grok-code-fast-1
  - name: goose
    model_name: gemini/gemini-2.5-pro
  - name: goose
    model_name: gemini/gemini-2.5-flash
  - name: goose
    model_name: together_ai/Qwen/Qwen3-Coder-480B-A35B-Instruct-FP8
  - name: goose
    model_name: together_ai/openai/gpt-oss-120b
  - name: goose
    model_name: together_ai/OpenAI/gpt-oss-20B
  - name: goose
    model_name: together_ai/moonshotai/Kimi-K2-Instruct-0905
  - name: goose
    model_name: together_ai/meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8
  - name: goose
    model_name: together_ai/zai-org/GLM-4.5-Air-FP8
  - name: goose
    model_name: together_ai/deepseek-ai/DeepSeek-V3.1
datasets:
  - path: ../sandboxes/tasks/sandboxes-tasks
    exclude_task_names:
      - chem-rf
      - hf-lora-adapter
      - leelachess0-pytorch-conversion
      - mcmc-sampling-stan
      - oom
      - privilege-escalation
      - shell-deobfuscation
      - speech-to-text
      - unprivileged-headless-pyrender
      - build-linux-kernel-qemu
      - caffe-cifar-10
      - install-windows-xp
      - kv-store-grpc
      - lean4-proof
      - mailman
      - predicate-pushdown-bench
      - protocol-analysis-rs
      - query-optimize
      - rstan-to-pystan
      - torch-pipeline-parallelism
      - word2vec-from-scratch
